-- This file has been generated by Dungeon Editor 2.2.4

-- TODO: place your custom dungeon object definitions here
defineObject{
   name = "user_ceiling",
   components = {
    {
      class = "Model",
      model = "mod_assets/models/romanusCeiling.fbx",
    },
  },
  placement = "ceiling",
  replacesWall = true,
}
