-- This file has been generated by Dungeon Editor 2.2.4
defineSound{
	name		= "customWaterFootsteps",
	filename	= "mod_assets/sounds/customWaterFootsteps.wav",
	loop		= false,
	volume		= 0.75,
	minDistance = 3,
	maxDistance = 3,
}

-- TODO: place your custom sound definitions here
